#!/usr/bin/env bash
# Static checks on a packaged kestrel output directory (no boot).
#
#   verify-static.sh OUT_DIR
#
# Extracts the RPMs into a scratch root and checks what the manifest claims:
#   one kernel directory, its name equals manifest.kver
#   vmlinuz is a signed EFI image whose embedded version string equals kver
#   every module is zstd compressed, signed, and one in-tree plus every
#   NVIDIA module verify against kestrel.crt
#   every NVIDIA module has vermagic == kver and version == manifest.nvidia
#   depmod resolves with no missing symbols
#   RPM provides carry the names Fedora tooling looks for
# Everything prints; nothing is trusted from a log.

# shellcheck disable=SC2015  # "test && ok || bad" is intended; ok never fails
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/lib.sh"
need rpm rpm2cpio cpio zstd depmod modinfo sbverify openssl file jq python3 rpmkeys

out=$(readlink -f "${1:?usage: verify-static.sh OUT_DIR}")
manifest="$out/manifest.json"
[[ -f $manifest ]] || die "no manifest at $manifest"
kver=$(jget "$manifest" .kver)
nvver=$(jget "$manifest" .nvidia.version)
cert="$out/kestrel.crt"
pass=0; fail=0
ok() { pass=$((pass+1)); printf 'PASS %s\n' "$*"; }
bad() { fail=$((fail+1)); printf 'FAIL %s\n' "$*"; }
check() { if "$@" >/dev/null 2>&1; then ok "$*"; else bad "$*"; fi; }

root=$(mktemp -d)
trap 'rm -rf "$root"' EXIT
group "Extract RPMs into $root"
for r in "$out"/rpms/*.rpm; do
  (cd "$root" && rpm2cpio "$r" | cpio -idmu --quiet)
  log "$(basename "$r") $(rpm -qp --qf '%{SIZE}' "$r" 2>/dev/null | numfmt --to=iec) payload"
done
endgroup

group "Layout"
dirs=$(find "$root/usr/lib/modules" -mindepth 1 -maxdepth 1 -type d | wc -l)
[[ $dirs -eq 1 ]] && ok "exactly one kernel directory" || bad "$dirs kernel directories"
[[ -d $root/usr/lib/modules/$kver ]] && ok "directory is $kver" || bad "kernel directory is not $kver"
[[ ! -e $root/boot || -z $(ls -A "$root/boot") ]] && ok "nothing in /boot" || bad "/boot is not empty"
[[ -f $root/usr/lib/modules/$kver/vmlinuz ]] && ok "vmlinuz present" || bad "vmlinuz missing"
[[ -f $root/usr/lib/modules/$kver/System.map && -f $root/usr/lib/modules/$kver/config ]] && ok "System.map and config present" || bad "System.map/config missing"
[[ -L $root/usr/lib/modules/$kver/build && $(readlink "$root/usr/lib/modules/$kver/build") == "/usr/src/kernels/$kver" ]] && ok "build symlink -> /usr/src/kernels/$kver" || bad "build symlink wrong"
[[ -f $root/usr/src/kernels/$kver/Module.symvers && -x $root/usr/src/kernels/$kver/scripts/basic/fixdep ]] && ok "devel tree has Module.symvers and scripts" || bad "devel tree incomplete"
[[ -f $root/usr/lib/modules/$kver/initramfs.img ]] && bad "initramfs shipped (must be generated by the consumer)" || ok "no initramfs in the artifact"
endgroup

group "Kernel image"
vz="$root/usr/lib/modules/$kver/vmlinuz"
file "$vz" | grep -q 'Linux kernel x86 boot executable' && ok "bzImage format" || bad "not a bzImage: $(file -b "$vz")"
emb=$(file -b "$vz" | grep -oE 'version [^ ]+' | awk '{print $2}')
[[ $emb == "$kver" ]] && ok "embedded version $emb == kver" || bad "embedded version '$emb' != $kver"
sbverify --cert "$cert" "$vz" >/dev/null 2>&1 && ok "vmlinuz Authenticode signature verifies with kestrel.crt" || bad "sbverify failed"
endgroup

group "Modules"
n_all=$(find "$root/usr/lib/modules/$kver" -name '*.ko*' | wc -l)
n_zst=$(find "$root/usr/lib/modules/$kver" -name '*.ko.zst' | wc -l)
[[ $n_all -eq $n_zst && $n_zst -gt 1000 ]] && ok "$n_zst modules, all zstd" || bad "$n_all modules, $n_zst zstd"
unsigned=0
while IFS= read -r -d '' f; do
  zstd -dcq "$f" | tail -c 28 | grep -q '~Module signature appended~' || unsigned=$((unsigned+1))
done < <(find "$root/usr/lib/modules/$kver" -name '*.ko.zst' -print0)
[[ $unsigned -eq 0 ]] && ok "every module carries a signature" || bad "$unsigned unsigned modules"
sample=$(find "$root/usr/lib/modules/$kver/kernel" -name '*.ko.zst' | sort | sed -n '1p;100p;1000p')
# shellcheck disable=SC2086
python3 "$KESTREL_ROOT/scripts/modsig.py" --cert "$cert" $sample "$root"/usr/lib/modules/"$kver"/extra/nvidia/*.ko.zst \
  && ok "sampled in-tree and all NVIDIA signatures verify against kestrel.crt" || bad "signature verification"
for m in nvidia nvidia-modeset nvidia-drm nvidia-uvm nvidia-peermem; do
  ko="$root/usr/lib/modules/$kver/extra/nvidia/$m.ko.zst"
  [[ -f $ko ]] || { bad "$m.ko.zst missing"; continue; }
  vm=$(modinfo -F vermagic "$ko" | awk '{print $1}')
  ver=$(modinfo -F version "$ko" 2>/dev/null || true)
  [[ $vm == "$kver" ]] && ok "$m vermagic $vm" || bad "$m vermagic $vm"
  if [[ $m != nvidia-peermem ]]; then
    [[ $ver == "$nvver" ]] && ok "$m version $ver" || bad "$m version '$ver' != $nvver"
  fi
done
modinfo -F vermagic "$root/usr/lib/modules/$kver/extra/nvidia/nvidia.ko.zst" | grep -q 'preempt' && ok "nvidia vermagic carries preempt flags: $(modinfo -F vermagic "$root/usr/lib/modules/$kver/extra/nvidia/nvidia.ko.zst")" || true
# Sanity on the kernel's own idea of a few things.
grep -q '^CONFIG_LTO_CLANG_THIN=y' "$root/usr/lib/modules/$kver/config" && ok "config: ThinLTO" || bad "config: no ThinLTO"
grep -q '^CONFIG_X86_64_VERSION=3' "$root/usr/lib/modules/$kver/config" && ok "config: x86-64-v3" || bad "config: not v3"
grep -q '^CONFIG_DEFAULT_SECURITY_SELINUX=y' "$root/usr/lib/modules/$kver/config" && ok "config: SELinux default" || bad "config: SELinux not default"
grep -q '^CONFIG_DEBUG_INFO_BTF=y' "$root/usr/lib/modules/$kver/config" && ok "config: BTF" || bad "config: no BTF"
grep -q '^CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3=y' "$root/usr/lib/modules/$kver/config" && ok "config: -O3" || bad "config: not -O3"
grep -q '^CONFIG_MODULE_SIG_FORCE=y' "$root/usr/lib/modules/$kver/config" && log "note: MODULE_SIG_FORCE is on" || ok "config: MODULE_SIG_FORCE off (sig_enforce is a karg choice)"
endgroup

group "depmod"
if depmod -b "$root/usr" -e -F "$root/usr/lib/modules/$kver/System.map" "$kver" 2>"$root/depmod.err"; then
  if grep -q -i 'unknown symbol\|needs unknown' "$root/depmod.err"; then bad "depmod: unresolved symbols: $(head -3 "$root/depmod.err")"; else ok "depmod resolves every module"; fi
else
  bad "depmod exited non-zero: $(head -3 "$root/depmod.err")"
fi
grep -q 'extra/nvidia/nvidia-drm.ko.zst:.*nvidia-modeset' "$root/usr/lib/modules/$kver/modules.dep" && ok "modules.dep: nvidia-drm depends on nvidia-modeset" || bad "modules.dep: nvidia chain missing"
endgroup

group "RPM metadata"
krpm=$(ls "$out"/rpms/kestrel-kernel-[0-9]*.rpm | head -1)
nrpm=$(ls "$out"/rpms/kestrel-nvidia-kmod-*.rpm | head -1)
drpm=$(ls "$out"/rpms/kestrel-kernel-devel-*.rpm | head -1)
prov=$(rpm -qp --provides "$krpm" 2>/dev/null)
for p in "kernel-uname-r = $kver" "kernel-core" "kernel = "; do
  grep -q "^$p" <<<"$prov" && ok "kestrel-kernel provides $p" || bad "kestrel-kernel lacks $p"
done
nprov=$(rpm -qp --provides "$nrpm" 2>/dev/null)
for p in "nvidia-kmod = 3:$nvver" "kmod-nvidia = 3:$nvver"; do
  grep -q "^$p" <<<"$nprov" && ok "kestrel-nvidia-kmod provides $p" || bad "kestrel-nvidia-kmod lacks $p"
done
grep -q "^kernel-uname-r = $kver" <<<"$(rpm -qp --requires "$nrpm" 2>/dev/null)" && ok "kestrel-nvidia-kmod requires kernel-uname-r = $kver" || bad "kmod requires wrong"
grep -q "^kernel-devel-uname-r = $kver" <<<"$(rpm -qp --provides "$drpm" 2>/dev/null)" && ok "devel provides kernel-devel-uname-r" || bad "devel provides"
for r in "$krpm" "$nrpm" "$drpm"; do
  [[ -z $(rpm -qp --scripts "$r" 2>/dev/null) ]] && ok "$(basename "$r"): no scriptlets" || bad "$(basename "$r") has scriptlets"
done
endgroup

group "RPM signatures"
if [[ $(jq -r '.signing.rpm.key // "none"' "$manifest") == project ]]; then
  [[ -f $out/RPM-GPG-KEY-kestrel ]] && ok "RPM-GPG-KEY-kestrel shipped" || bad "RPM public key missing"
  # A private rpmdb so the check does not need root or touch the host's keyring.
  dbpath=$(mktemp -d); rpmkeys --dbpath "$dbpath" --import "$out/RPM-GPG-KEY-kestrel" >/dev/null 2>&1 || true
  for r in "$out"/rpms/*.rpm; do
    rpmkeys --dbpath "$dbpath" --define '_pkgverify_level all' --checksig "$r" >/dev/null 2>&1 \
      && ok "$(basename "$r") signature verifies with RPM-GPG-KEY-kestrel" || bad "$(basename "$r") signature check failed"
  done
  rm -rf "$dbpath"
else
  log "note: RPMs unsigned (signing.rpm.key = $(jq -r '.signing.rpm.key // "none"' "$manifest"))"
fi
endgroup

group "Manifest consistency"
for r in "$out"/rpms/*.rpm; do
  n=$(basename "$r"); want_sha=$(jq -r --arg n "$n" '.rpms[] | select(.name==$n) | .sha256' "$manifest")
  [[ $want_sha == "$(sha256_of "$r")" ]] && ok "manifest sha256 matches $n" || bad "manifest sha256 mismatch $n"
done
fpr=$(openssl x509 -in "$cert" -noout -fingerprint -sha256 | cut -d= -f2)
[[ $(jq -r .signing.certificate.sha256_fingerprint "$manifest") == "$fpr" ]] && ok "manifest cert fingerprint matches kestrel.crt" || bad "cert fingerprint mismatch"
[[ $(jq -r .signing.key "$manifest") == project ]] && ok "signed with the project key" || log "note: signing.key = $(jq -r .signing.key "$manifest")"
endgroup

printf '\nstatic verification: %d passed, %d failed\n' "$pass" "$fail"
[[ $fail -eq 0 ]]
