# kestrel-kernel: CachyOS kernel built for Fedora bootc images.
#
# All content is prepared by scripts/package.sh in %{kestrel_stage}; this spec
# only wraps the tree. No scriptlets: kestrel-install runs depmod and dracut.
#
# Macros passed on the rpmbuild command line:
#   kestrel_stage   staging root with the final file tree
#   kver            kernel release string, e.g. 7.2.3-2-cachyos
#   kversion        upstream version, e.g. 7.2.3
#   krelease        RPM release, e.g. 2.kestrel.fc44
#   channel         stable or lts
#   filelist_core   file list for the main package
#   filelist_devel  file list for the devel package

%global __os_install_post %{nil}
%global __spec_install_post %{nil}
%global debug_package %{nil}
%global _build_id_links none
%global __strip /bin/true
%global __brp_mangle_shebangs %{nil}
%global __brp_check_rpaths %{nil}
%global _binary_payload w19.zstdio
%global _rpmformat 4
%global _unpackaged_files_terminate_build 0
%global _missing_doc_files_terminate_build 0

Name:           kestrel-kernel
Version:        %{kversion}
Release:        %{krelease}
Summary:        CachyOS %{channel} kernel %{kver} for bootc images (kestrel)
License:        GPL-2.0-only
URL:            https://github.com/mheci/kestrel
ExclusiveArch:  x86_64
AutoReqProv:    no

Provides:       kernel = %{version}-%{release}
Provides:       kernel-core = %{version}-%{release}
Provides:       kernel-modules = %{version}-%{release}
Provides:       kernel-modules-core = %{version}-%{release}
Provides:       kernel-modules-extra = %{version}-%{release}
Provides:       kernel-uname-r = %{kver}
Provides:       kestrel-kernel(channel) = %{channel}
Requires:       kmod
Requires:       coreutils

%description
The CachyOS %{channel} kernel (%{kver}) compiled by kestrel with Clang
ThinLTO for x86-64-v3, signed with the kestrel project key. Contains the
kernel image, in-tree modules, System.map and config under
/usr/lib/modules/%{kver}. No initramfs: run kestrel-install or dracut.

%package devel
Summary:        Headers and build scripts for building modules against %{kver}
License:        GPL-2.0-only
AutoReqProv:    no
Provides:       kernel-devel = %{version}-%{release}
Provides:       kernel-devel-uname-r = %{kver}
Provides:       kernel-devel-matched = %{version}-%{release}
Requires:       kestrel-kernel = %{version}-%{release}
# The build scripts inside are dynamically linked binaries (fixdep, modpost,
# objtool, resolve_btfids); these are their runtime libraries. The compiler
# is on purpose not required: a bootc image keeps devel headers for
# auditing without carrying clang.
Requires:       elfutils-libelf
Requires:       openssl-libs
Recommends:     clang
Recommends:     lld
Recommends:     llvm
Recommends:     make

%description devel
Kernel headers, Module.symvers and the scripts needed to build out-of-tree
modules against kestrel kernel %{kver}. The kernel is built with Clang
ThinLTO; build external modules with LLVM=1.

%prep
%build

%install
cp -a %{kestrel_stage}/. %{buildroot}/

%files -f %{filelist_core}
%files devel -f %{filelist_devel}

%changelog
# Generated by kestrel; see /usr/share/kestrel/manifest.json for provenance.
