# kestrel-nvidia-kmod: NVIDIA open GPU kernel modules built for one kestrel kernel.
#
# Macros passed on the rpmbuild command line:
#   kestrel_stage  staging root containing usr/lib/modules/<kver>/extra/nvidia
#   kver           kernel release string
#   nvver          NVIDIA driver version, e.g. 610.57.04
#   nvrelease      RPM release, e.g. 1.kestrel.fc44
#   channel        stable or lts
#   filelist       file list

%global __os_install_post %{nil}
%global __spec_install_post %{nil}
%global debug_package %{nil}
%global _build_id_links none
%global __strip /bin/true
%global _binary_payload w19.zstdio
%global _rpmformat 4
%global _unpackaged_files_terminate_build 0
%global _missing_doc_files_terminate_build 0

Name:           kestrel-nvidia-kmod
Version:        %{nvver}
Release:        %{nvrelease}
Epoch:          3
Summary:        NVIDIA open kernel modules %{nvver} for kestrel kernel %{kver}
License:        MIT AND GPL-2.0-only
URL:            https://github.com/NVIDIA/open-gpu-kernel-modules
ExclusiveArch:  x86_64
AutoReqProv:    no

# What Terra's and RPM Fusion's userspace packages look for. The epoch and
# version match Terra's nvidia-driver so `nvidia-kmod-common = 3:<ver>` resolves.
Provides:       nvidia-kmod = %{epoch}:%{version}
Provides:       nvidia-kmod = %{epoch}:%{version}-%{release}
Provides:       kmod-nvidia = %{epoch}:%{version}
Provides:       kmod-nvidia = %{epoch}:%{version}-%{release}
Provides:       kmod-nvidia-%{kver} = %{epoch}:%{version}-%{release}
Provides:       kmod-nvidia-open = %{epoch}:%{version}
Provides:       nvidia-open-kmod = %{epoch}:%{version}
Provides:       kestrel-nvidia-kmod(channel) = %{channel}
Requires:       kernel-uname-r = %{kver}
Conflicts:      akmod-nvidia
Conflicts:      kmod-nvidia-open-dkms
Conflicts:      nvidia-open-kmod-dkms

%description
The NVIDIA open GPU kernel modules (nvidia, nvidia-modeset, nvidia-drm,
nvidia-uvm, nvidia-peermem) version %{nvver}, built by kestrel against
kernel %{kver} with the kernel's own toolchain and signed with the kestrel
project key. Pair with nvidia-driver %{nvver} from Terra or RPM Fusion for the
userspace and GSP firmware.

%prep
%build

%install
cp -a %{kestrel_stage}/. %{buildroot}/

%files -f %{filelist}

%changelog
# Generated by kestrel; see /usr/share/kestrel/manifest.json for provenance.
